//
// EventCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class EventCreate: JSONEncodable {

    public var yelpID: String?
    public var title: String?
    public var description: String?
    public var purpose: String?
    public var startTime: String?
    public var minAge: Double?
    public var maxAge: Double?
    public var capacity: Double?
    public var gender: String?
    /** user current location, will be updated to restaurant location later */
    public var lng: Double?
    /** user current location, will be updated to restaurant location later */
    public var lat: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["yelpID"] = self.yelpID
        nillableDictionary["title"] = self.title
        nillableDictionary["description"] = self.description
        nillableDictionary["purpose"] = self.purpose
        nillableDictionary["startTime"] = self.startTime
        nillableDictionary["minAge"] = self.minAge
        nillableDictionary["maxAge"] = self.maxAge
        nillableDictionary["capacity"] = self.capacity
        nillableDictionary["gender"] = self.gender
        nillableDictionary["lng"] = self.lng
        nillableDictionary["lat"] = self.lat

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
