//
// ProfileUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ProfileUpdate: JSONEncodable {

    public var displayName: String?
    public var email: String?
    public var phone: String?
    public var avatar: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["displayName"] = self.displayName
        nillableDictionary["email"] = self.email
        nillableDictionary["phone"] = self.phone
        nillableDictionary["avatar"] = self.avatar

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
