//
// Promotion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Promotion: JSONEncodable {

    public enum PromotionType: String { 
        case featured = "featured"
        case discount = "discount"
        case deal = "deal"
    }
    public var yelpID: String?
    public var name: String?
    public var contact: String?
    public var email: String?
    public var phone: String?
    public var country: String?
    public var province: String?
    public var city: String?
    public var street: String?
    public var promotionType: PromotionType?
    public var startDate: String?
    public var endDate: String?
    public var startHour: String?
    public var endHour: String?
    public var price: String?
    public var amount: Double?
    public var item: String?
    public var images: [String]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["yelpID"] = self.yelpID
        nillableDictionary["name"] = self.name
        nillableDictionary["contact"] = self.contact
        nillableDictionary["email"] = self.email
        nillableDictionary["phone"] = self.phone
        nillableDictionary["country"] = self.country
        nillableDictionary["province"] = self.province
        nillableDictionary["city"] = self.city
        nillableDictionary["street"] = self.street
        nillableDictionary["promotionType"] = self.promotionType?.rawValue
        nillableDictionary["startDate"] = self.startDate
        nillableDictionary["endDate"] = self.endDate
        nillableDictionary["startHour"] = self.startHour
        nillableDictionary["endHour"] = self.endHour
        nillableDictionary["price"] = self.price
        nillableDictionary["amount"] = self.amount
        nillableDictionary["item"] = self.item
        nillableDictionary["images"] = self.images?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
