//
// RestaurantLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class RestaurantLocation: JSONEncodable {

    public var address1: String?
    public var address2: String?
    public var address3: String?
    public var city: String?
    public var zipCode: String?
    public var country: String?
    public var state: String?
    public var displayAddress: [String]?
    public var crossStreets: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["address1"] = self.address1
        nillableDictionary["address2"] = self.address2
        nillableDictionary["address3"] = self.address3
        nillableDictionary["city"] = self.city
        nillableDictionary["zip_code"] = self.zipCode
        nillableDictionary["country"] = self.country
        nillableDictionary["state"] = self.state
        nillableDictionary["display_address"] = self.displayAddress?.encodeToJSON()
        nillableDictionary["cross_streets"] = self.crossStreets

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
