//
// Restaurant.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Restaurant: JSONEncodable {

    public var id: String?
    public var name: String?
    public var imageUrl: String?
    public var url: String?
    public var isClaimed: Bool?
    public var isClosed: Bool?
    public var phone: String?
    public var categories: RestaurantCategories?
    public var rating: Double?
    public var location: RestaurantLocation?
    public var coordinates: RestaurantCoordinates?
    public var photos: [String]?
    public var hours: RestaurantHours?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["image_url"] = self.imageUrl
        nillableDictionary["url"] = self.url
        nillableDictionary["is_claimed"] = self.isClaimed
        nillableDictionary["is_closed"] = self.isClosed
        nillableDictionary["phone"] = self.phone
        nillableDictionary["categories"] = self.categories?.encodeToJSON()
        nillableDictionary["rating"] = self.rating
        nillableDictionary["location"] = self.location?.encodeToJSON()
        nillableDictionary["coordinates"] = self.coordinates?.encodeToJSON()
        nillableDictionary["photos"] = self.photos?.encodeToJSON()
        nillableDictionary["hours"] = self.hours?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
