//
// Event.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Event: JSONEncodable {

    public var id: String?
    public var yelpID: String?
    public var title: String?
    public var description: String?
    public var purpose: String?
    public var startTime: String?
    public var minAge: Double?
    public var maxAge: Double?
    public var capacity: Double?
    public var gender: String?
    public var attendees: [Profile]?
    public var author: Profile?
    public var hasFinished: Bool?
    public var lng: Double?
    public var lat: Double?
    public var createdAt: String?
    public var updatedAt: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["yelpID"] = self.yelpID
        nillableDictionary["title"] = self.title
        nillableDictionary["description"] = self.description
        nillableDictionary["purpose"] = self.purpose
        nillableDictionary["startTime"] = self.startTime
        nillableDictionary["minAge"] = self.minAge
        nillableDictionary["maxAge"] = self.maxAge
        nillableDictionary["capacity"] = self.capacity
        nillableDictionary["gender"] = self.gender
        nillableDictionary["attendees"] = self.attendees?.encodeToJSON()
        nillableDictionary["author"] = self.author?.encodeToJSON()
        nillableDictionary["hasFinished"] = self.hasFinished
        nillableDictionary["lng"] = self.lng
        nillableDictionary["lat"] = self.lat
        nillableDictionary["createdAt"] = self.createdAt
        nillableDictionary["updatedAt"] = self.updatedAt

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
