//
// Profile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Profile: JSONEncodable {

    public var id: String?
    public var facebookID: String?
    public var firebaseID: String?
    public var firstname: String?
    public var displayName: String?
    public var lastname: String?
    public var gender: String?
    public var email: String?
    public var birthday: String?
    public var avatar: String?
    public var phone: String?
    public var createdAt: String?
    public var updatedAt: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["facebookID"] = self.facebookID
        nillableDictionary["firebaseID"] = self.firebaseID
        nillableDictionary["firstname"] = self.firstname
        nillableDictionary["displayName"] = self.displayName
        nillableDictionary["lastname"] = self.lastname
        nillableDictionary["gender"] = self.gender
        nillableDictionary["email"] = self.email
        nillableDictionary["birthday"] = self.birthday
        nillableDictionary["avatar"] = self.avatar
        nillableDictionary["phone"] = self.phone
        nillableDictionary["createdAt"] = self.createdAt
        nillableDictionary["updatedAt"] = self.updatedAt

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
