//
// RestaurantAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class RestaurantAPI: APIBase {
    /**

     - parameter id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getRestaurantById(id: String, completion: @escaping ((_ data: InlineResponse2001?,_ error: Error?) -> Void)) {
        getRestaurantByIdWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /restaurants/{id}
     - get restaurant detailed info by yelp id
     - examples: [{contentType=application/json, example={
  "restaurants" : [ {
    "hours" : {
      "is_open_now" : true,
      "hours_type" : "aeiou"
    },
    "image_url" : "aeiou",
    "rating" : 0.80082819046101150206595775671303272247314453125,
    "coordinates" : {
      "latitude" : 6.02745618307040320615897144307382404804229736328125,
      "longitude" : 1.46581298050294517310021547018550336360931396484375
    },
    "photos" : [ "aeiou" ],
    "url" : "aeiou",
    "is_claimed" : true,
    "phone" : "aeiou",
    "name" : "aeiou",
    "location" : {
      "country" : "aeiou",
      "cross_streets" : "aeiou",
      "address3" : "aeiou",
      "address2" : "aeiou",
      "city" : "aeiou",
      "address1" : "aeiou",
      "display_address" : [ "aeiou" ],
      "state" : "aeiou",
      "zip_code" : "aeiou"
    },
    "id" : "aeiou",
    "categories" : {
      "alias" : "aeiou",
      "title" : "aeiou"
    },
    "is_closed" : true
  } ]
}}]
     
     - parameter id: (path)  

     - returns: RequestBuilder<InlineResponse2001> 
     */
    open class func getRestaurantByIdWithRequestBuilder(id: String) -> RequestBuilder<InlineResponse2001> {
        var path = "/restaurants/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<InlineResponse2001>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
